name: media_mate
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.0
  provider: ^6.1.5
  google_fonts: ^6.3.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  firebase_storage: ^13.0.0
  intl: ^0.20.2
  mask_text_input_formatter: ^2.9.0
  timezone: ^0.9.4
  flutter_timezone: ^4.1.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

