include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics

linter:
  rules:
    prefer_single_quotes: true

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 6
    maximum-nesting-level: 5
    source-lines-of-code: 120
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics-exclude:
    - test/**
    - build/**
  rules:
    - newline-before-return
    - no-equal-then-else
    - prefer-trailing-comma
    - avoid-non-null-assertion
    - avoid-late-keyword
    - avoid-unused-parameters:
        allowed-names:
          - _
    - no-boolean-literal-compare
    - prefer-const-border-radius
