// it teaches Firebase how to connect to your specific Firebase project depending on the platform.

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhW9olP_AnFCi2QZrk7WCB-RJSXktPZwU',
    appId: '1:768201889581:web:72097cda34b92f0b3fa5a4',
    messagingSenderId: '768201889581',
    projectId: 'media-mate-7d7c9',
    authDomain: 'media-mate-7d7c9.firebaseapp.com',
    storageBucket: 'media-mate-7d7c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJKMj_EZGeawDnOqOGGgmQX3PAULjzdjE',
    appId: '1:768201889581:android:d855bac90a9553a63fa5a4',
    messagingSenderId: '768201889581',
    projectId: 'media-mate-7d7c9',
    storageBucket: 'media-mate-7d7c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVO-v5Bw4vV-8kzrsNdPBx5YgITEafsqI',
    appId: '1:768201889581:ios:60f97dff357406d73fa5a4',
    messagingSenderId: '768201889581',
    projectId: 'media-mate-7d7c9',
    storageBucket: 'media-mate-7d7c9.firebasestorage.app',
    iosClientId:
        '768201889581-rrudej9bocqt3o97h2mpt5rkf90cvu9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediaMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVO-v5Bw4vV-8kzrsNdPBx5YgITEafsqI',
    appId: '1:768201889581:ios:60f97dff357406d73fa5a4',
    messagingSenderId: '768201889581',
    projectId: 'media-mate-7d7c9',
    storageBucket: 'media-mate-7d7c9.firebasestorage.app',
    iosClientId:
        '768201889581-rrudej9bocqt3o97h2mpt5rkf90cvu9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediaMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhW9olP_AnFCi2QZrk7WCB-RJSXktPZwU',
    appId: '1:768201889581:web:ba41db8b7b40a12c3fa5a4',
    messagingSenderId: '768201889581',
    projectId: 'media-mate-7d7c9',
    authDomain: 'media-mate-7d7c9.firebaseapp.com',
    storageBucket: 'media-mate-7d7c9.firebasestorage.app',
  );
}
